### ISSUE TITLE
We should be able to customize the app even more

### ISSUE THREAD

**Issue by Okamille** [SwipesForScience/SwipesForScience#40]
I've started to do it a bit in the last commits in #38 .
But we don't have an efficient way to refer to the assets for the badges + we can move the text from a lot of pages to configuration so it's not directly written in the code.

**Comment by richford** [comment]
I definitely agree with the sentiment here and would like to see a lot of customization moved into `config.json`. But I think this conversation might be better had as a GitHub discussion, rather than as an issue, since it's a bit vague at the moment.

I'm going to close this for now. Please feel free to reopen as a discussion.
